server:
  port: 8999
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: employee-service
        uri:
          lb://employee-service
        predicates:
        - Path=/employees/**
      - id: department-service
        uri:
          lb://department-service
        predicates:
        - Path=/departments/**
      - id: college-service
        uri:
          lb://college-service
        predicates:
        - Path=/college/**
      - id: student-service
        uri:
          lb://student-service
        predicates:
        - Path=/student/**
